### ISSUE TITLE
Bring back original convention on sorting imports

### ISSUE THREAD

**Issue by hvelarde** [plone/plone.api#187]
as per discussion in https://github.com/plone/plone.recipe.codeanalysis/issues/88#issuecomment-63073852, I suggest to remove the following phrase from the [plone.api](https://github.com/plone/plone.api/blob/master/docs/contribute/conventions.rst#grouping-and-sorting) conventions:

_As for sorting, it is recommended to use case-sensitive sorting. This means uppercase characters come first, so "Products.*" goes before "plone.*"._

example should also be fixed.

this commit can be reverted: https://github.com/plone/plone.api/commit/8cfe6da47319ff71725eef2bfab6378ef1280909

**Comment by jaroel** [comment]
The only reason we're preferring case sensitive sorting is because of tooling.
When this was decided, the defacto editor (ST2) and mr.igor sorted case sensitive, so we went with that.

imho plone.recipe.codeanalysis should be leading, therefor plone.api should change the conventions.

**Comment by zupo** [comment]
What do you mean by leading?

**Comment by jaroel** [comment]
That plone.recipe.codeanalysis specifies what the coding standard should be. I'd like it to check all code, instead of doing it myself.

**Comment by gforcada** [comment]
@jaroel circular dependency here though as p.r.codeanalysis is supposed to encode Plone's styleguide which, by now, is maintained here in plone.api :)

(sorry for the SPAM :)

**Comment by jaroel** [comment]
@gforcada true, true. *meh*

**Comment by saily** [comment]
Can we finalize this? I'd like to release `plone.recipe.codeanalysis 2.0` as Plone 5 ready. I don't care how to sort it, i just want to know the rule we should verify against. @jensens, @tisto, can you take that into a FWT meeting?

**Comment by tisto** [comment]
Will do...

**Comment by hvelarde** [comment]
I asked advice from the UX experts: http://ux.stackexchange.com/q/79259/46964

**Comment by hvelarde** [comment]
Now that we have [evidence that non-case sensitive sorting is better](http://ux.stackexchange.com/a/79266/46964), can we move on with this ticket and bring back original convention?

**Comment by jensens** [comment]
in other words we fix the documentation to prefer the use of non-case-sensitive sorting. that's what i prefer too.
:+1:

**Comment by do3cc** [comment]
@hvelarde I've followed your question on the ux mailing list and I feel it is misleading.
The original reason for sorting wasn't for readability, but for avoiding complex diffs because people change the imports to their liking.

The sort order does not matter at all for finding things quicker in the import list, if you want to look something up, you are always looking up a term imported via a from statement and the word you are looking for will be the last word in the line. I am not sure how sorting by the first word helps here.

My vim sorts case sensitive by default (:sort) 
emacs too
http://www.gnu.org/software/emacs/manual/html_node/emacs/Sorting.html
sublime text is configurable
Pycharm does grouping, which is wrong altogether according to our plone.api documentation.

As I see it, case insensitive sorting adds more work to most developers, the argument of readability fails because it misses the point for what you are actually looking for.

**Comment by jensens** [comment]
as "sort order does not matter ar all": what about leaving it as it is _now_ and focusing on other more important topics?

**Comment by do3cc** [comment]
case sensitive sorting is what is implemented right now but marked as a bug :-)

**Comment by adamcheasley** [comment]
I agree with @jensens here. Although I'd prefer case sensitive sorting, of all the bugs that we have, surely this is the least important?

**Comment by do3cc** [comment]
Is this a bug tracker? Isn't one of the functions of a bug tracker to track bugs so that one doesn't have to track them all in his brain?
If you don't want to weight in your opinion now, do it later

**Comment by adamcheasley** [comment]
I've already made my opinions clear...in November last year (see above). However, it's ordering imports. It's subjective. I really don't think this is worth reopening.

**Comment by hvelarde** [comment]
![hn1uu](https://cloud.githubusercontent.com/assets/341393/9787229/5737cc60-5797-11e5-8187-e1b0d1b0d08e.jpg)

**Comment by do3cc** [comment]
Hi Hector,

I am not going to reply to this on github because as others have said, it is not important right now.

This stupid meme image drags the argument on a personal level by implying that I did not read on the discussion that happened before.
It moves the discussion away from the arguments I have given and which I doubt you disagree with.

You could also just have said Fuck off and that is the message that got across. I am not sure if that was your goal.

On 10 Sep 2015, at 13:39, Héctor Velarde <notifications@github.com<mailto:notifications@github.com>> wrote:


[hn1uu]<https://cloud.githubusercontent.com/assets/341393/9787229/5737cc60-5797-11e5-8187-e1b0d1b0d08e.jpg>

—
Reply to this email directly or view it on GitHub<https://github.com/plone/plone.api/issues/187#issuecomment-139210427>.

________________________________________________________ The contents of this e-mail and any attachments are confidential to the intended recipient. They may not be disclosed to or used by or copied in any way by anyone other than the intended recipient. If this e-mail is received in error, please immediately notify the sender and delete the e-mail and attached documents. Please note that neither the sender nor the sender's company accept any responsibility for viruses and it is your responsibility to scan or otherwise check this e-mail and any attachments.

**Comment by hvelarde** [comment]
may I ask why this is still open? bug reports are already open in plone.recipe.codeanalysis:

* https://github.com/plone/plone.recipe.codeanalysis/issues/97
* https://github.com/plone/plone.recipe.codeanalysis/issues/163

**Comment by do3cc** [comment]
@hvelarde Because of these arguments https://github.com/plone/plone.api/issues/187#issuecomment-139180596
The other issues are about implementation, this is about best practices. In particular the second issue does not contest the idea of case insensitive sorting but complains that the latest codeanalysis does NOT honour the best practices currently in the docs.

**Comment by hvelarde** [comment]
it's really amazing the amount of time and energy we have wasted on this until now; leave it open, if you want but... if as you say "sort order does not matter at all", then we can just remove that convention and let people do whatever they want with the imports, even don't sort anything as they can find quicker using the find command of the editor of their choice.

**Comment by do3cc** [comment]
The quote is incomplete, here is the longer form:
The sort order does not matter at all *for finding things quicker in the import list , if you want to look something up, you are always looking up a term imported via a from statement and the word you are looking for* **will be the last word in the line.**
Sorting is important for clean code, because it reduces useless diffs when people reorder imports again and again to personal preferences.
I do not see this as wasted time, we want to have a good solution, it makes sense to think it through.
So far, you did ignore my arguments, instead of trying to stay constructive, your last only attacked me as a person. But my skin is thick enough :-)

**Comment by hvelarde** [comment]
@do3cc this is getting worse: where do I attacked you as a person on my comment? this is a complete non-sense, you don't need to play the victim... the level is getting lower with each comment.

**Comment by do3cc** [comment]
https://github.com/plone/plone.api/issues/187#issuecomment-139210427

**Comment by jcbrand** [comment]
FWIW, I'm personally +1 for keeping the sentence and I think @do3cc's argument of keeping diffs readable is valid.

In any case, as the text says, it's just a recommendation and plone.recipe.codeanalysis doesn't enforce it. So I don't see the point of making a big deal out of it.

**Comment by rnixx** [comment]
16 Nov 2014 to 18 Nov 2015. Not bad :8ball:

**Comment by do3cc** [comment]
@jcbrand The discussion is actually about what should be default, case sensitive or case insensitve sorting.
There is general consonsus already that sorting is the way to go.
plone.recipe.codeanalysis has a sort order checker and it will only accept one of the two sortings valid

**Comment by hvelarde** [comment]
@do3cc you think that's personal? seriously? your skin is thinner than you think then.

@jcbrand case insensitive sorting gives you that AND gives readability, that's the whole point of the issue.

@rnixx yes, and seem it will continue until... Nov 2016? 2017? 2020? you guess...

**Comment by jcbrand** [comment]
@doc3cc Oh, that's not what I gathered from reading the [linked to ticket](https://github.com/plone/plone.recipe.codeanalysis/issues/88). The consensus appeared to be to not check the order. Granted, I don't know what the actual code looks like.

Personally, I think would still stick with the status quo, otherwise everything needs to be changed again, for IMHO negligible and subjective benefit.

**Comment by do3cc** [comment]
@jcbrand Since the sorting plugin in plone.app.codeanalysis is currently broken anyway, it can still be changed (again, actually) :-)

**Comment by jcbrand** [comment]
I'd keep the recommendation and drop the checking of imports in plone.app.codeanalysis. Then everyone's (un)happy! :D

**Comment by do3cc** [comment]
@hvelarde Yes, your comments were personal attacks or misinterpretations. At no time since september did you participate in this discussion in a constructive manner

**Comment by rnixx** [comment]
@hvelarde @do3cc Things won't get better. Whats the default behavior of line sorting in the most spreaded editors? Make this default... my 2c

**Comment by do3cc** [comment]
@rnixx from https://github.com/plone/plone.api/issues/187#issuecomment-139180596

My vim sorts case sensitive by default (:sort)
emacs too
http://www.gnu.org/software/emacs/manual/html_node/emacs/Sorting.html
sublime text is configurable
Pycharm does grouping, which is wrong altogether according to our plone.api documentation.

That is my argument all the time already :-) :+1:

**Comment by rnixx** [comment]
Eclipse also does case sensitive sorting. So fine.

BTW - I cannot find anything really offensive either. Let's keep out such stuff and leave it to professional victims and SJW's.

peace

**Comment by gforcada** [comment]
@do3cc it's starting to get irritating that you keep saying that p.r.codeanalysis checker is broken, since it's perfectly stable and doing whatever you tell it to do (via .isort.cfg)

Another completely different thing is what you like to be the default, which, again can be fixed on isort itself.

The bonus point of isort is that, by default, fixes imports, not only reports, so any cleanup is just one command away.

**Comment by jensens** [comment]
I cant follow, whats the discussion about?

**Comment by do3cc** [comment]
@gforcada plone.recipe.codeanalysis does not create the .isort.cfg file. When adding plone.recipe.codeanalysis with [recommended] extras, the isort checker will show imports, ordered to plone.api conventions as false. I consider this a broken behavior, this is why the ticket is open again. 

Let us keep the *broken* discussion off this ticket, we got plone/plone.recipe.codeanalysis#163 for that.

The different point about what should be the default, it is fine if one can customize the isort behavior, then we may end with different rules for each plone package? I am not totally against that, because the ISort tool also provides the command to format everything according to rules

The bonus point is fine, I already got it working in vim, most of the time. In some projects it does not seem to work and I fail to debug it. I am also not sure, if it is possible to add the Isort plug in to all editors which are in common use.

May I summarize your comment as a third option for following one common standard:
- Sort Case Sensitive
- Sort Case Insensitive
- Sort whatever people like in a package, but document it via .isort.cfg and optionally enforce it via plone.app.codeanalysis

Is there a consensus on the advantages and disadvantes of each option:

Option | possible in vim | possible in emacs | possible in eclipse | possible in pycharm
----------|------------|---------------|---------------|--------------------------------------------------
Sort case sensitive | yes | yes | yes | no (Only weird sort order)
Sort case insensitive | yes (with special suffix) | ? | ? | no (Only weird sort order)
ISort support sort | yes (minor issues with virtualenv) | ?(probaly) | ? | ?

**Comment by hvelarde** [comment]
@do3cc from the very beginning I was very open to discussion and I was very constructive: I even brought opinions from experts outside the community; trying to deny that is futile. we can have a conversation with arguments and opinions, not only opinions.

as I said before the only difference among case sensitive and case insensitive sorting, is that the later is better for human readability; tools should work for the sake of people and not the other way around.

if the problem for you was technical, then we were talking about different things; from your resume I don't see any technical limitation as almost all editors are capable of case insensitive sorting:

**vim**: http://superuser.com/a/793783
**emacs**: http://stackoverflow.com/a/20967895
**eclipse**: https://marketplace.eclipse.org/content/anyedit-tools

**gedit** also supports case insensitive sort.

now, if you want to keep wasting time an energy on this, just because you don't like case insensitive sorting, then I vote for removing the whole thing from the Plone API conventions and end of problem.

**Comment by zupo** [comment]
"the later is better for human readability;" -> that's subjective and an opinion. For me, case sensitive is more readable. 

And since case sensitive is what more editors do by default, we chose it as the guideline. If there are no objective arguments against case sensitive ("more readable" without a source proving it is moot), then "more common for editors" is the only one we can work with.

**Comment by saily** [comment]
ok, just to get this thing and https://github.com/plone/plone.recipe.codeanalysis/issues/163 closed, i suggest (and yes, i'll volunteer implementing this) writing an `flake8-isort-plone` plugin, which is based on the great work @gforcada did, which passes - by default - our conventions into `SortImports` here: https://github.com/gforcada/flake8-isort/blob/master/flake8_isort.py#L14

So it's up to everyone's guidelines to customize this with and `.isort.cfg`, but by default we force our conventions when enabling `flake8-isort-plone` plugin. 

The only thing left is that we just finalize our guidelines. 
Should we start a poll, or @tisto, do we decide this as a testing team?

**Comment by hvelarde** [comment]
@zupo no, is not an opinion, is a fact; you have double work looking for something case sensitive: first you have to know if it is upper or lower case and then you have to check the order.

**Comment by do3cc** [comment]
@hvelarde I hate to repeat my argument from https://github.com/plone/plone.api/issues/187#issuecomment-139180596 but
**What** are you looking up?

You want to know from which package `ICatalog` is coming from.

How does sort order help here:

from Products.ZCatalog.interfaces import **ICatalog**

you never want to know if you import from `Products.ZCatalog` so it really is a mood point if case insensitive or case sensitive sorting makes you find things faster.

Instead of adding findability, case insensitive sorting adds work to contributors who first must figure out how to change their editors defaults.

**Comment by fulv** [comment]
I'm gonna regret stepping into this, but taking @hvelarde's example (
https://github.com/plone/Products.Archetypes/blob/master/Products/Archetypes/atapi.py),
look at the two sortings:

https://gist.github.com/fulv/f794f91eafaf9b08bc03

If anyone can convince me that one is better than the other when trying to
find out, e.g., where CompositeSchema is imported from, I'll buy them a
case of beer.

**Comment by hvelarde** [comment]
@do3cc you're not looking for consensus; you simply don't want to have type an additional character when sorting, and that's totally fine. you just have to say that clearly.

@fulv readability and searchability are different things; you will never search for text by reading the whole file.

**Comment by thet** [comment]
@fulv me too!

but what about this sorting: https://gist.github.com/thet/ddff81b4eec013f4f8c8

it's sorted on the last word in an import statement.
with this vim command '`:sort /.* /'' it's sorted that way. everything, which matches the pattern in ``//`` will be ignored by sort.

**Comment by do3cc** [comment]
@thet that is a funny solution :-)

**Comment by do3cc** [comment]
@hvelarde Are you saying that you want case insensitive search for better readability and not for better searchability?

Why do you read import lines, if not for finding things?

Regarding the "I don't want to have to type an additional character". It is a bit more involved for setting up sorting. This adds stop energy for new contributors or contributors who rarely contribute and did not set up their editor to handle case insensitive sorting. This is just a tiny bit of stop energy, but I am sure I am not the only one who stopped providing a pull request because suddenly tests didn't pass for obscure reasons.

Why adding this stop energy if readability is not a prime concern? The major reason for sorting import lines is that diffs stay small and merges get easier because the order is deterministic and everybody agrees to it. So the simplest solution, the one most editors do out of the box, is perfectly fine.

**Comment by zupo** [comment]
This ^

**Comment by hvelarde** [comment]
@do3cc just look what I've found: https://github.com/zopefoundation/zc.relation/commit/10b9f88ab8530ab4c0eca86416a7200d84b3e5d1

ROFL

**Comment by do3cc** [comment]
Does silence mean consensus for the default being sort case sensitive?
For reference:
```
from a import A
from a import Z
from a import a
from a import z
```

**Comment by jaroel** [comment]
@thet Here's how I would order it: https://gist.github.com/jaroel/4bdd0e7a0093ae7cc46b

@do3cc I don't care. As long as isort case do this for me, I'm game :)

**Comment by hvelarde** [comment]
seems that somebody erased a previous post with this: https://github.com/zopefoundation/zc.relation/commit/10b9f88ab8530ab4c0eca86416a7200d84b3e5d1

as I said before ROFL.

**Comment by do3cc** [comment]
@jaroel: Cool! Just for the record, Since today I argue to remove flake8-isort from the recommended section of plone.app.codeanalysis, I added a bunch of reasons here: https://github.com/plone/plone.recipe.codeanalysis/issues/163#issuecomment-165058772
If this would become reality. it would mean you have to declare your flake8-isort dependency explicitly. I hope that would not be a big deal.

**Comment by jaroel** [comment]
@do3cc Not a problem at all!

**Comment by do3cc** [comment]
@hvelarde I feel sad that it wasn't you who deleted your embarrassing comment. Even more so as you repeat it again. 

I hope you understand that to outsiders you do not only represent yourself but Plone, the community. 

Maybe you want to delete that message yourself this time.

**Comment by thet** [comment]
@jaroel nice example! only i really don't like multi line imports for readability reasons.

**Comment by jensens** [comment]
@jaroel in fact we used this way in a lot of bluedynamics code in past, but it does not help so much with finding a string by quick scanning of the import block.

Anyway, if we want to support the programmer in my opinion sorting should happen after the imported thing, such as:

    from lorem import Aadfasd
    from ipsum import absadfgasdg
    from dolor import baasddgsadg
    from sit import Bbasdfgasdfg
    from amet import Fbasdfgfsrg

But since theres no tool support (neither anybody else does it) I'd stick to simple insensitive alphanumeric sorting.

**Comment by hvelarde** [comment]
@do3cc no, I don't want to delete my comment and I want to say something more: if you were the person who erased it, be careful on misusing the powers you have: you have absolutely no right to delete someone else's comments not violating the [Code of Conduct](https://plone.org/foundation/materials/foundation-resolutions/code-of-conduct).

**Comment by do3cc** [comment]
@hvelarde I didn't delete it and I wouldn't, it doesn't feel right to do such a thing.

**Comment by hvelarde** [comment]
thank you; have a nice holiday.

**Comment by do3cc** [comment]
@jensens finally gave a compelling reason: He already converted way to much code in Plone to the style. That is the winning argument.

**Comment by gforcada** [comment]
I'm closing this one then. Whoever feels to keep discussing follow to https://github.com/plone/documentation/pull/509
