### ISSUE TITLE
Javascript should have 4 spaces for indent

### ISSUE THREAD

**Issue by rodfersou** [plone/plone.api#231]
Come-on guys we are from Python world, legibility counts, I don't agree to use 2 spaces as indentation for any code file..

http://docs.plone.org/external/plone.api/docs/contribute/conventions.html#editorconfig

In the end it will be compressed on production, so there is no problem to add more spaces as indentation!

**Comment by hvelarde** [comment]
:+1:

**Comment by tisto** [comment]
Why should we use Python best practices in Javascript? Last time I checked 2 blanks were the way to go in the Javascript community. 

2 blanks are in no way less readable than 4 blanks. I'm not aware of any research that would support that claim. Compression was never a pro argument either.

If you want to change our best practice (we already had a long discussion about that, please check the issues), please provide strong evidence that the JS community uses 4 blanks instead of 2. Otherwise I would suggest to close this issue.

**Comment by tisto** [comment]
A few links about 2 vs 4 tabs in the JS community:

https://seravo.fi/2013/javascript-the-winning-style
https://github.com/feross/standard
http://atroche.org/post/30994290348/javascript-indentation

**Comment by miohtama** [comment]
Though I personally would prefer 4 spaces, I find the resources and the majority voting for 2 spaces in JS. JS is often nested callback spaghetti, so maybe they have some sense here. 

Well, time to adjust my editor then!

**Comment by hvelarde** [comment]
I think evidence is incontestable, @rodfersou :cactus:

**Comment by rodfersou** [comment]
I think it is easy to talk to follow the best practices language when you just write one language code, but if you switch from Python to Javascript many times, this is not good for your brain.

I'm talking about readability, not fighting with other communities best practices.

But I understand your position @tisto and respect even if it will be a PITA for my eyes.
