### ISSUE TITLE
Allow to trigger events on objects

### ISSUE THREAD

**Issue by gforcada** [plone/plone.api#299]
I'm not sure if it fits on the 80/20 rule, but I have quite a calls to ``notify(IRandomEvent(obj))`` which could be nice to be done via plone.api.

Something like ``plone.api.content.notify(obj, event, *data)`` as a signature?

Opinions?

**Comment by hvelarde** [comment]
+1

**Comment by thet** [comment]
You're not saving any lines of code with that, but if you're like me you're saving time to look up the syntax of doing event notifications. It's a bit like zope.event, which itself is only one line of code, if you don't count the import.
I'm +0.5 for this ;)

I also support @hvelarde's suggestion of **not** putting this in ``plone.api.content``. IMO it doesn't belong there, because you can pass any object with notify. But creating an ``plone.api.event`` module would be too much overhead for only the notify API method. I guess you would not find anything else useful in such an event module? Maybe ``plone.api.portal`` or a new ``plone.api.utils`` instead?

**Comment by tomgross** [comment]
I don't see any advantage / simplification. More a cause for confusion. *plone.api.portal*, *plone.api.content* or *plone.api.utils*?
```
from zope.event import notify
notify(MyEvent(object))
```
is straight forward IMO.

**Comment by thet** [comment]
yes, it is.

**Comment by gforcada** [comment]
I agree that you are not saving lines of code, but you are saving imports and direct dependencies (so you don't have to remember were they belong).

But I'm also ok to not add it.
