### ISSUE TITLE
Why we are not testing against Plone 4.3?

### ISSUE THREAD

**Issue by hvelarde** [plone/plone.api#367]
I just discovered that PR are not being tested against Plone 4.3; AFAIK, Plone 4.3 is still supported and the lack of testing is opening the door to bugs like #364.

**Comment by gforcada** [comment]
It is tested (supposedly): https://github.com/plone/plone.api/blob/master/.travis.yml#L9 where is 4.3 missing?

**Comment by hvelarde** [comment]
from Jenkins; you can confirm that on any PR.

**Comment by mauritsvanrees** [comment]
Nothing in 4.3 core is using plone.api, and it is not in the version pins or in the sources. Also, plone.api has only been officially added in Plone 5.0. So it seems normal that it is not tested on Jenkins for 4.3.

Travis tests it with the latest Plone 4.3 release. That should be good enough. Regressions caused by a new Plone release will be caught the next time a Travis job is run. plone.api can then be fixed and a new release made.

But yes, if we wanted to, we could probably test plone.api on Jenkins 4.3 too, to catch regressions caused by changes to core packages before they end up in a release.
Actually: it may be tricky: it can only be done by adding `plone.api` to the test eggs so it ends up in the `bin/test` script. And this means that other core packages could start to depend on `plone.api` without us noticing it, if reviewers aren't careful.
So the best way then would be to create a `bin/test-with-plone-api` script and run the `plone.api` tests with that. It should be doable, but I am not enthousiastic. It would need changes to the Jenkins scripts so this new test script is run. Or `bin/alltests` would somehow need to use the `bin/test` script for all packages except for `plone.api` which would need to be run with the new script.
Given this complexity, I am inclined to let it go.

**Comment by hvelarde** [comment]
thanks for the clarification.
