### ISSUE TITLE
api.content.create fails to create a Plone4 AT Collection

### ISSUE THREAD

**Issue by gbastien** [plone/plone.api#413]
Hi everybody, @david-batranu 

it fails in archetypes/querywidget/widget.py because the form given to process_form is {None: None} and values are not iterable.

This is due to a recent change, so either we change {None: None} to {'': ''} or we have to change archetypes.querywidget.  Would {'': ''} sove your problem @david-batranu because it solves our ;-)

Thank you!

Gauthier

**Comment by hvelarde** [comment]
@gbastien we already created a failing test on the referenced pull request.

**Comment by david-batranu** [comment]
@gbastien A lot of time has passed, and don't remember exactly why I chose `{None: None}` as the "empty" value.  

The purpose of the fix was for the `if` in [BaseObject.process_form](https://github.com/plone/Products.Archetypes/blob/master/Products/Archetypes/BaseObject.py#L606) to pass, so that `form = values` instead of getting polluted by the `request.form` data. Looks like `{'': ''}` would pass this check as well. I'm not sure of any side-effects. I guess if the tests pass, it's ok :)

All of my findings are described on https://github.com/plone/plone.api/issues/99#issuecomment-364390511

**Comment by gbastien** [comment]
@david-batranu 

thank you for feedback, I think {'':''} will have the same behavior and it solves the problem...  I proposed this change to @idgserpro and @hvelarde 

Gauthier

**Comment by hvelarde** [comment]
fixed in #414
