### ISSUE TITLE
Drop Plone Support < 5.2

### ISSUE THREAD

**Issue by jensens** [plone/plone.api#450]
I propose to drop support of Plone < 5.2 for plone.api. Otherwise adding of new features gets very complex (looking at the relations PR).

**Comment by mauritsvanrees** [comment]
@plone/framework-team Is anyone against this?

I have gone ahead and made a branch 1.10.x. For good measure I have updated coredev 4.3 and 5.1 to use this.

**Comment by ale-rt** [comment]
Some consideration:
- I think we can easily drop AT support and keep support for Plone 5.2.
- I am not against dropping support for Python 2 (I bet it will work well enough on Plone 5.2 + Python3 as well, at least as long as the planned relations module is not used).
- if needed I think some fixes can be backported to 1.10.x quite easily

Personally I would say go ahead.
But I would really like to hear other opinions from @plone/framework-team

**Comment by ale-rt** [comment]
Sorry I misread the title :)
That said my "go ahead" is even more firm!

**Comment by jensens** [comment]
Dropping Plone 5.2 in combination of dropped Py 2.7 and dropped AT support in a 2.x series sounds like a plan, while keeping the 1.x series supporting 4.3, 5.1 and 5.2 on Py2.7 and with AT.

**Comment by mauritsvanrees** [comment]
> Dropping Plone 5.2 in combination of dropped Py 2.7 and dropped AT support in a 2.x series sounds like a plan.

Sounds confusing. This looks like dropping 5.2 support is different from dropping Py 2 and AT. But maybe I just misinterpret you.
I don't want to drop 5.2 support yet. The plan is to add the relations support to 5.2, which means supporting Python 2.7. Should be easy enough, because as far as I know the collective.relationhelpers code works on Py 2.7.
So my preference:

- 1.10.x: support 4.3-5.2, Py 2+3
- 1.11.x: add relation module, support 5.2-6.0, Py 2+3
- master/2.x: only support 6.0 Py 3.

**Comment by mauritsvanrees** [comment]
As expected, it seems there is no opposition to dropping support for Plone 5.1 and earlier. I have merged my changes to that effect in [PR 431](https://github.com/plone/plone.api/pull/431#pullrequestreview-603947042). Once it is green, for me it is fine to merge.
