### ISSUE TITLE
Create 2.0 without support for Python 2 and Archetypes

### ISSUE THREAD

**Issue by pbauer** [plone/plone.api#460]
As mentioned in https://github.com/plone/plone.api/pull/449 I propose to have a plone.api version 2.0 that only targets Plone 6 and above. The code and tests could be cleaned up and simplified in many places. 
Also nobody would expect the new api methods for relations to work with Archetypes. 

TODOs:
- [x] Cleanup code to remove Archetypes-specific code
- [x] Update code (e.g. using pyupgrade) to only support Python 3
- [ ] Document changes

**Comment by tisto** [comment]
@pbauer +1 for getting rid of old cruft. For plone.restapi we decided to support both Plone 5.2 and Plone 6 (with Python 3 only and without AT of course). The tradeoff was that when you have a Plone 5.2 version (that lots of people will still use) you will have to do lots of backporting between the branches. When you have a Plone 5.2/Plone 6 it does not cost much to support both (because they are very close) but you avoid to much backporting in the future. Just my 2c...

Maybe the @plone/framework-team should put that on their agenda for the next meeting and make some general suggestions on how core packages should handle things. I know @jensens also has some valuable insights to share on the topic...

**Comment by pbauer** [comment]
Compared to plone.restapi there is very little active development happening in plone.api (it is pretty stable). I don't think there will be a lot of backporting necessary. 
On the other hand it would be nice to be able to use the new relations-api in 5.2.x without having to use collective.relationhelpers. The framework-team should decide.

**Comment by ale-rt** [comment]
I like the idea of a version 2 supporting only Plone 6.

My thoughts on this:
1. Plone 5.2 is close to the end of it's development cycle.
2. I am a bit shy of adding new features and making revolutions on something that should be really stable.
3. This is a core package, not an add-on.
4. Adding plone.api features to Plone 5.2 that are not working with all the Python versions Plone 5.2 should support is a mistake. 
5. Investing additional resources to also warrant support Plone 5.2 and Python3 looks a waste (and a risk) to me.
6. There will be a moment (hopefully soon), when core developers will be on Plone 6 only and they will hardly be able to maintain the package for Plone 5.2

What do the other @plone/framework-team members think about this?

**Comment by frapell** [comment]
I agree with everything @ale-rt mentioned. Especially with point 4, so I think it is a good idea to have 2.0 for Plone 6 onwards.

**Comment by pbauer** [comment]
All relevant tests (Plone 6 only) are green now. The coredev for 5.2 is updated to use the new branch 1.x. So if the framework-team agrees we could go ahead and merge #461
