### ISSUE TITLE
Redirect api.plone.org after relaunch of Plone 6 documentation

### ISSUE THREAD

**Issue by ksuess** [plone/plone.api#471]
**correct addresses:**
plone.api Version **2.x:** https://6.dev-docs.plone.org/plone.api
plone.api Version **1.x**: https://docs.plone.org/develop/plone.api/docs/index.html and api.plone.org
The distinction is important cause version 2.x introduces for example the new module `relation`

**broken links to plone.api documentation:**
https://docs.plone.org/develop/plone.api/docs/ (found in Google results and is the redirect of api.plone.org)
https://docs.plone.org/develop/plone.api/docs/index.html (Found on https://docs.plone.org/develop/plone/getstarted/index.html#plone-resources and other pages of docs.plone.org)

**This can be removed:** 
https://readthedocs.org/projects/ploneapi/ (found in Google results searching for plone.api)

**Comment by stevepiercy** [comment]
Also https://api.plone.org/ redirects to a 404 at https://docs.plone.org/develop/plone.api/docs as reported by @erral. This should instead redirect to https://6.dev-docs.plone.org/plone.api/

@plone/ai-team

**Comment by stevepiercy** [comment]
See also https://github.com/plone/documentation/issues/1140

**Comment by polyester** [comment]
Fixed; to get around our limited number of redirects for cloudflare (redirects count different from DNS, as you can't point to a URL with DNS I've used the [Cloudflare Bulk Redirect feature](https://developers.cloudflare.com/rules/bulk-redirects/concepts/), which will give us 10k redirects, which hopefully should be enough to clean up old URL's ...

**Comment by stevepiercy** [comment]
> docs.plone.org/plone.api
> 
> By now https://6.dev-docs.plone.org/plone.api

@ksuess was `docs.plone.org/plone.api` ever a valid URL? Where does it appear?

**Comment by ksuess** [comment]
The links in docs.plone.org to plone.api documentation are broken. Who has access to correct them? The links are https://docs.plone.org/develop/plone.api/docs/index.html, etc. and should either go to new Plone 6 documentation (hints have to be added, that `relations` is available in 2.x) or we should provide a version 1.x build. What do you think?

**Comment by ksuess** [comment]
Same question for api.plone.org: redirect to new Plone 6 documentation or to a plone.api version 1.x build?

**Comment by stevepiercy** [comment]
The plone.api docs appear to not get pulled in for Plone 5.x. [They were pulled in for Plone 4.x](https://docs.plone.org/4/en/external/plone.api/docs/index.html). I think that the plone.api docs should get pulled into the main documentation for Plone 5.x as they were for Plone 4.x, but I have absolutely no idea how to do that. @polyester do you have any idea?

I don't have any other options for how to archive a version of plone.api 1.x for Plone 5.

-----

All the plone.api doc pages on RTD are archived. We should either delete the content entirely, or set up a redirects for all of its URLs. The current implementation for only the index page is not good. Who has power to do that?

- https://ploneapi.readthedocs.io/en/latest/ -> https://6.dev-docs.plone.org/plone.api/
- https://ploneapi.readthedocs.io/en/latest/content.html -> no redirect

-----

For `api.plone.org`, I think that RTD was on to something with the concept of `latest` as a synonym for the latest stable version number. IOW, when we release v6 of docs, `latest` would be aliased to `6` and these URLs would point to the same physical resource.

- https://6.docs.plone.org/foo
- https://latest.docs.plone.org/foo

When 7 comes out, then `latest` would be aliased to `7`. This way we can always have links to `latest` that never need to change (unless the path changes, of course), or to previous versions for archival reference.

**Comment by polyester** [comment]
@stevepiercy the reason plone.api docs were not pulled in is because it was pulling in 'master', which has switched to markdown as format, and the 5.x build process speaks rst only... 

Specifying that for plone 5.x docs it should pull in the 1.x branch does the trick, see [here](https://github.com/plone/papyrus/commit/ff0d16a81c957327860ce934291af7209e8da28d)

Change deployed to docs.plone.org, so the 5.x docs has plone.api 1.x docs embedded in them.

**Comment by stevepiercy** [comment]
Thanks, @polyester.

I think that `api.plone.org` should now redirect to https://docs.plone.org/develop/plone.api/docs/index.html because Plone 6 has not been released. Sorry for flip-flopping, but that content wasn't there earlier.

-----

@zupo @wormj would you please grant both @stevepiercy and @ksuess access to https://readthedocs.org/projects/ploneapi/? We should purge it and [all of its versions](https://readthedocs.org/projects/ploneapi/versions/) to prevent search engine indexing. Alternatively I could contact RTD to set up a large volume of redirects, instead of doing onesies for all pages across all versions. I'd prefer to purge, as the last successful build was 5 years, 11 months ago for [1.0.0-rc.1](https://ploneapi.readthedocs.io/en/1.0.0-rc.1/).

-----

We can discuss `latest`, `5`, `6`, `7`, and future versions in https://github.com/plone/documentation/issues/1140#issuecomment-1136430009. It's more of a global docs issue than just one package.

**Comment by zupo** [comment]
> @zupo @wormj would you please grant both @stevepiercy and @ksuess access to https://readthedocs.org/projects/ploneapi/? We should purge it and [all of its versions](https://readthedocs.org/projects/ploneapi/versions/) to prevent search engine indexing. Alternatively I could contact RTD to set up a large volume of redirects, instead of doing onesies for all pages across all versions. I'd prefer to purge, as the last successful build was 5 years, 11 months ago for [1.0.0-rc.1](https://ploneapi.readthedocs.io/en/1.0.0-rc.1/).

Done!

**Comment by stevepiercy** [comment]
I deleted the RTD project. Eventually it will be removed from search engine indexing.

Last ToDo is for @polyester to update the redirect, and then this issue can be closed.

**Comment by polyester** [comment]
done

**Comment by stevepiercy** [comment]
Thank you!
