### ISSUE TITLE
api.content.create replaces archetype-content title with site title during Plone site creation

### ISSUE THREAD

**Issue by datakurre** [plone/plone.api#99]
How to reproduce:
1. Use `plone.api.content.create` to create content in "setuphandlers.py" (or custom GS profile configuration step).
2. Create a new Plone site and select the profile in question to be installed for the new site.

Then

Each new Archetype-based content object created with plone.api.content.create will have site title as its title.

Why
1. plone.api.content.create calls Archetypes' processForm-method
2. processForm-method tries to re-fill content fields from request
3. title-widget finds a title field from the request (because the default form for creating a new Plone site has a title field)

Our local fix is to pop "title" key from the request.form before running code with plone.api.content.create.

But note that this is not limited to the site creation from but any values in request.form may cause similar surprises with api.content.create.

If it's not a feature to read field values for plone.api.content.create from request, then maybe request.form should somehow be cleared before creating Archetypes-content and restored afterwise.

**Comment by jaroel** [comment]
What needs to be done, and who is going to do it?

**Comment by pgrunewald** [comment]
I am also interested in getting this issue solved.

Maybe we could use the `values` parameter of processForm and populate it with dictionary containing `title` (if present) and all other passed data from kwargs. That way the request object is not consulted, when retrieving potential form data.

**Comment by david-batranu** [comment]
The changes introduced in https://github.com/plone/plone.api/commit/f73bddc570c05f7a1a4cea01c75b1cea6538676e breaks content creation when other fields are involved. Consider this usecase:

``` Python
from datetime import datetime

from Products.Archetypes import atapi
from Products.ATContentTypes.content import schemata
from Products.ATContentTypes.content import base

from plone import api


class IMyContent(Interface):
    """ """

MyContentSchema = schemata.ATContentTypeSchema.copy() + atapi.Schema((

    atapi.DateTimeField(
        'date',
        schemata='default',
        required=True,
        languageIndependent=True,
    ),
)


class MyContent(base.ATCTContent):
    implements(IMyContent)

    meta_type = 'MyContent'
    schema = MyContentSchema


atapi.registerType(MyContent, 'my.package')

def do_manual_creation(context):
    fields = {'title': 'A title', 'date': datetime.now()}
    content = api.content.create(context, 'MyContent', id='mycontent', **fields)

    # pre 1.6.1:
    # >>> type(content.date)
    # <type 'datetime.datetime'>

    # post 1.6.1
    # >>> type(content.date)
    # <type 'NoneType'>
```

This is because `CalendarWidget.process_form` is called with `fields` as `form`. That method does some [insane](https://github.com/plone/Products.Archetypes/blob/master/Products/Archetypes/Widget.py#L469) things, completely ignoring the passed value and finally returning `''` which gets saved by `DateTimeField` as `None`.

Pre 1.6.1, `form` was `request.form`, set by [`BaseObject._processForm`](https://github.com/plone/Products.Archetypes/blob/master/Products/Archetypes/BaseObject.py#L606), so in the abve usecase, `date` would be completely missing from the form, resulting in `empty_marker` to be returned by the widget, and the field to not be mutated; the value set by `invokeFactory` preserved.

I believe a better solution for `plone.api.content.create` would be to replace `processForm(values=kwargs)` with `processForm(values={})`. From what I can see, widgets mostly do the right thing and return `empty_marker` if `field.getName()` is missing from the request. Perfect when programatically adding content through `invokeFactory`/`plone.api.content.create` as the set values don't get modified.

I will make a pull request, with the change.

**Comment by gotcha** [comment]
@david-batranu Did you check that the bug with title mentioned above by @datakurre is still fixed ?

**Comment by david-batranu** [comment]
@gotcha you're right! I fixed the pull request, it now uses a `{None: None}` dict, so it will pass the check in  [`BaseObject._processForm`](https://github.com/plone/Products.Archetypes/blob/master/Products/Archetypes/BaseObject.py#L606).
